import { Styles } from "../../globals.slint";

export component ResponseBody inherits VerticalLayout {
    out property<string> body;

    Text {
        height: 3%;
        font-size: Styles.font_size;
        text: "Body";
    }

    Rectangle {
        border-color: gray;
        border-width: 1px;
        border-radius: 5px;

        VerticalLayout {
            padding: Styles.padding;
            
            TextInput {
                single-line: false;
                text <=> body;
            }
        }
    }
}