import { Response } from "../../structs/response.slint";
import { HeaderText } from "../header-text.slint";
import { ResponseBar } from "response-bar.slint";
import { ResponseHeaders } from "response-headers.slint";
import { ResponseBody } from "response-body.slint";

export component Response inherits VerticalLayout {
    in property<Response> response;
    in property<bool> has_error;

    HeaderText {
        text: "Response";
    }
    
    if root.response.status_code > 0 && !root.has_error: VerticalLayout {
        ResponseBar {
            response: root.response;
        }

        ResponseHeaders {
            headers: root.response.headers;
        }

        ResponseBody {}
    }

    if root.response.status_code == 0 && !root.has_error: VerticalLayout {
        HorizontalLayout {
            alignment: center;

            Text {
                text: "No response";
            }
        }
    }

    if root.has_error: VerticalLayout {
        HorizontalLayout {
            alignment: center;

            Text {
                text: "Could not connect to the server";
            }
        }
    }
}