import { LineEdit, Button } from "std-widgets.slint";
import { Header } from "../structs/header.slint"; 
import { Styles } from "../globals.slint";

export component RequestHeader {
    in property<Header> header;

    callback edit_name(string);
    callback edit_value(string);
    callback remove();

    HorizontalLayout {
        spacing: Styles.spacing;

        LineEdit {
            text: header.name;

            edited(value) => root.edit_name(value);
        }

        LineEdit {
            text: header.value;

            edited(value) => root.edit_value(value);
        }

        Button {
            text: "X";
            
            clicked => root.remove();
        }
    }
}