import { Button, StyleMetrics } from "std-widgets.slint";
import { RequestHeader } from "request-header.slint";
import { Header } from "../structs/header.slint";
import { Styles } from "../globals.slint";

export component RequestHeaders {
    in property<[Header]> headers;

    callback add();
    callback edit_name(int, string);
    callback edit_value(int, string);
    callback remove(int);

    VerticalLayout {
        spacing: Styles.spacing;
    
        Text {
            font-size: Styles.text-size;
            text: "Headers";
        }

        Button {
            width: 50px;
            text: "+";

            clicked => root.add();
        }

        for header[i] in root.headers: RequestHeader {
            header: header;
            
            edit_name(value) => root.edit_name(i, value);
            edit_value(value) => root.edit_value(i, value);
            remove => root.remove(i);
        }
    }
}