import { TextEdit } from "std-widgets.slint";
import { Styles } from "../../globals.slint";

export component RequestBody {
    in property<string> type;

    out property<string> body;

    if (type != "GET" && type != "DELETE"): VerticalLayout {
        spacing: Styles.spacing;
        
        Text {
            font-size: Styles.heading_font_size;
            text: "Body";
        }

        TextEdit {
            font-size: Styles.font_size;
            placeholder-text: "{\n    \"key\": \"value\"\n}";
            text <=> root.body;
        }
    }
}