import { TextEdit } from "std-widgets.slint";
import { Styles } from "../../globals.slint";

export component RequestBody {
    in property<string> type;

    out property<string> body;

    if (type != "GET" && type != "DELETE"): VerticalLayout {
        spacing: Styles.spacing;
        
        Text {
            height: 3%;
            font-size: Styles.font_size;
            text: "Body";
        }

        TextEdit {
            text <=> root.body;
        }
    }
}