import { Styles } from "../../globals.slint";

export component RequestBody {
    in property<string> type;

    out property<string> body;

    if (type != "GET" && type != "DELETE"): VerticalLayout {
        spacing: Styles.spacing;
        
        Text {
            height: 3%;
            font-size: Styles.text_size;
            text: "Body";
        }

        Rectangle {
            border-color: gray;
            border-width: 1px;
            border-radius: 5px;

            VerticalLayout {
                padding: Styles.padding;
                
                TextInput {
                    single-line: false;
                    text <=> body;
                }
            }
        }
    }
}