import { RequestHeader } from "components/request-header.slint";
import { RequestBar } from "components/request-bar.slint";
import { Header } from "structs/header.slint";
import { ComboBox, LineEdit, LineEdit, Button, ScrollView } from "std-widgets.slint";
import { RequestBody } from "components/request-body.slint";
import { RequestHeaders } from "components/request-headers.slint";
import { Styles } from "globals.slint";

export component AppWindow inherits Window {
    min-width: 720px;
    min-height: 400px;
    max-width: 3840px;
    max-height: 2160px;

    private property<string> type: bar.type;

    in property<[Header]> headers;

    callback send(url: string, type: string);
    callback add();
    callback edit_name(int, string);
    callback edit_value(int, string);
    callback remove(int);

    ScrollView {
        VerticalLayout {
            padding: Styles.padding;
            spacing: Styles.spacing;

            bar := RequestBar {
                send(url, type) => root.send(url, type);
            }

            RequestHeaders {
                headers: root.headers;
                
                add => root.add();
                edit_name(index, value) => root.edit_name(index, value);
                edit_value(index, value) => root.edit_value(index, value);
                remove(index) => root.remove(index);
            }

            RequestBody {
                type: root.type;
            }
        }
    }
}