
import { ScrollView } from "std-widgets.slint";
import { Styles } from "globals.slint";
import { Header } from "structs/header.slint";
import { Response } from "structs/response.slint";
import { Loader } from "components/loader.slint";
import { Request } from "components/request/request.slint";
import { Response } from "components/response/response.slint";

export component AppWindow inherits Window {
    min-width: 1024px;
    min-height: 576px;
    max-width: 3840px;
    max-height: 2160px;
    title: "Httpint";

    in property<[Header]> headers;
    in property<Response> response;
    in property<string> error;
    in property<bool> is_loading;

    callback send(url: string, type: string, body: string);
    callback add();
    callback edit_name(int, string);
    callback edit_value(int, string);
    callback remove(int);

    ScrollView {
        Loader {
            is_loading: root.is_loading;
        }
        
        HorizontalLayout {
            padding: Styles.padding;
            spacing: Styles.spacing;
            visible: !root.is_loading;

            request := Request {
                width: root.width * 0.6 - Styles.padding - Styles.spacing - divider.width;
                spacing: Styles.spacing;

                headers: root.headers;

                send(url, type, body) => root.send(url, type, body);
                add => root.add();
                edit_name(index, value) => root.edit_name(index, value);
                edit_value(index, value) => root.edit_value(index, value);
                remove(index) => root.remove(index);
            }

            divider := Rectangle {
                width: 1px;
                background: #808080;
            }

            Response {
                width: root.width * 0.4 - Styles.padding - Styles.spacing;
                spacing: Styles.spacing;

                response: root.response;
                error: root.error;
            }
        }
    }
}